databases:
  - name: Saitamap_production
    databaseName: Saitamap_production
    user: Saitamap
    region: singapore
    plan: free

services:
  - type: web
    name: Saitamap_production
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Saitamap_production
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
