default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Saitmap_development

test:
  <<: *default
  database: Saitmap_test

production:
  <<: *default
  database: Saitmap_production
  username: Saitamap
  password: <%= ENV['SAITAMAP_DATABASE_PASSWORD'] %>
  url: <%= ENV['DATABASE_URL'] %>
